### ISSUE TITLE
Need to setup Unit Tests

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/projectman#1]
If anyone wants to help me out by settings up unit tests for actions and other functions do comment here.

I will prefer Mocha and Chai for unit tests, let's discuss here if you want to use any other libraries

**Comment by codyaverett** [comment]
Personally I've never used either Mocha or Chai, but I have used [Ava](https://github.com/avajs/ava) for one project and [Jest](https://jestjs.io/)  for others. (:heart: jest's snapshot tests) 
[Substack's Tape](https://github.com/substack/tape) is another minimalistic testing lib that would suffice.

I like how by default jest and ava find all my test files and include expect/assert type logic in the test runtime.

Up to you, it's just tool opinions.  What do you think @saurabhdaware ?

**Comment by saurabhdaware** [comment]
I am not sure how Jest will handle command-line tests I read this article https://medium.com/@zorrodg/integration-tests-on-node-js-cli-part-1-why-and-how-fa5b1ba552fe which explained testing in CLI and they are using mocha and chai.

Though now I think the easier way would be to call the action functions rather than triggering the commands and reading the output.

**Comment by codyaverett** [comment]
That's cool @saurabhdaware.  Np and sounds just fine.

Food for thought, I also like this other cli framework called gluegun, they use jest to perform integration tests on their CLI. e.g. they test the outcome of a command such as files created and such, but they do test the terminal output some too.

https://github.com/infinitered/gluegun/blob/master/src/cli/cli.integration.ts

I'll fix the issue you brought up in my PR in a few.
