### ISSUE TITLE
Rust port...?

### ISSUE THREAD

**Issue by hskang9** [saurabhdaware/projectman#12]
Is is okay if I make this in rust?

**Comment by saurabhdaware** [comment]
That sounds like a great idea and yes you can go ahead! 
Also, it would be super nice of you if you mention link to this repo in your readme :)
and do send me the link of repo I would love to contribute as well

**Comment by hskang9** [comment]
Sure on my way

**Comment by hskang9** [comment]
https://github.com/hskang9/projectman-rust/blob/master/src/main.rs

Here it is.
