### ISSUE TITLE
Projects are erased after updating package

### ISSUE THREAD

**Issue by saurabhdaware** [saurabhdaware/projectman#2]
So when a user installs the package he gets settings.json in his `npm global directory/projectman/lib/settings.json`. Since it is also a part of package it is replaced with blank settings.json every time a user updates the package.

I can't really think of any way to stop this, Any ideas?

**Comment by codyaverett** [comment]
Hi @saurabhdaware 

What if we instead stored these settings in the users home directory? 
Could be something like `~/.projectmanrc` so it's simple to determine that this is the settings file for this tool.

If the file does not already exist, generate the file, then append to it.
If the file does exist, append to it.

**Comment by saurabhdaware** [comment]
Yeah, I was thinking about something similar. Any idea how Windows will handle this? I am sure it will work for Linux and Mac

**Comment by Tanuj69** [comment]
```JavaScript
const os = require("os")

```

**Comment by saurabhdaware** [comment]
> ```js
> const os = require("os")
> os.homedir(); // returns path to C:\\Users\test' whatever in windows and ~/ in Linux 
> ```

Cool, I'll try it out, thanks @Tanuj69

**Comment by saurabhdaware** [comment]
Done! 🎉 Resolved this is be70d72cacec184b8291a2af7e38ed027926e5
will release this along with some other changes in v1.1.0.
Thank you @codyaverett and @Tanuj69 :)
