### ISSUE TITLE
Listing all the added projects using `pm list`

### ISSUE THREAD

**Issue by backtrackbaba** [saurabhdaware/projectman#31]
What about adding an additional command `pm list` to list all the added projects. Would make it convenient to see the available projects and then choosing to open one of them

**Comment by saurabhdaware** [comment]
Currently `pm open` does list added projects is that what you mean?

**Comment by backtrackbaba** [comment]
Yup, I tend to do things like this. I used to use the `pm open <projectName>` directly. My bad, I tried `pm open` and that's exactly what I was looking for.

**Comment by saurabhdaware** [comment]
oh cool! thanks for using projectman 🌻🌻
