### ISSUE TITLE
Add possibility to don't open editor

### ISSUE THREAD

**Issue by bartekpacia** [saurabhdaware/projectman#8]
I'd find it very useful to have a possibility do don't use any editor, i.e I just want to `cd` to the project directory and don't open any editor.

I use Android Studio for some of my projects so it's annoying to close VSCode every time I use `pm open`.

**Comment by saurabhdaware** [comment]
Hi please go through latest comments in #7 . 
We can't exactly make a command to cd but we'll have something like `cd $(pm getPath <projectName>)`  in future version.

Thank you for giving your input :) . Closing this as #7  is similar to this
